# Server
#server.port=8093
#
#spring.kafka.bootstrap-servers=localhost:9092
#
#spring.kafka.consumer.properties.spring.json.value.default.type=com.emailsystem.emailer.model.EmailEvent
#spring.kafka.consumer.properties.spring.json.use.type.headers=false
#
## Mail - real Gmail
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=odiliejeh09@gmail.com
#spring.mail.password=zqlvwryjyyakgval
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true


spring.application.name=emailer
server.port=8093


# Kafka Consumer
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=email-group
spring.kafka.consumer.auto-offset-reset=earliest

# Wrap deserializers with error handler so bad messages are skipped not crash
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.emailsystem.emailer.model.AuctionEvent
spring.kafka.consumer.properties.spring.json.use.type.headers=false



# ── Gmail SMTP ───────────────────────────────────────────
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=odiliejeh09@gmail.com
spring.mail.password=zqlvwryjyyakgval
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true